name: dart_orm_adapter_postgresql
version: 0.0.9+1
description: >
  PostgreSQL adapter for DartORM
author: Ustimenko Sergey <ustims@gmail.com>
homepage: http://github.com/ustims/DartORM-PostgreSQL
dependencies:
  dart_orm: ">=0.0.4 <0.2.0"
  logging: ">=0.9.2 <0.12.0"
  postgresql: ">=0.3.0+2 <0.4.0"